name: Build and Publish Docker Images
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-and-publish:
    strategy:
      matrix:
        architecture: [debian, alpine, alpine-full]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build the Docker image
        run: docker build . --file ${{ matrix.architecture }}.Dockerfile --tag pedromr/collectd:${{ matrix.architecture }}-${{ steps.get_version.outputs.VERSION }}
      - name: Publish the Docker image
        run: |
          docker login -u ${{ secrets.DockerHubUsername }} -p ${{ secrets.DockerHubToken }}
          docker push pedromr/collectd:${{ matrix.architecture }}-${{ steps.get_version.outputs.VERSION }}
      - name: Publish the 'no-architecture' tag
        if: ${{ matrix.architecture == 'debian' }}
        run: |
          docker tag pedromr/collectd:${{ matrix.architecture }}-${{ steps.get_version.outputs.VERSION }} pedromr/collectd:${{ steps.get_version.outputs.VERSION }}
          docker push pedromr/collectd:${{ steps.get_version.outputs.VERSION }}
