name: Build and Publish Docker Images
on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-publish:
    strategy:
      matrix:
        architecture: [debian, alpine, alpine-full]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.architecture }}.Dockerfile --tag pedromr/collectd:${{ matrix.architecture }}-${{ github.ref }}
    - name: Publish the Docker image
      run: |
        docker login -u ${{ secrets.DockerHubUsername }} -p ${{ secrets.DockerHubToken }}
        docker push pedromr/collectd:${{ matrix.architecture }}-${{ github.ref }}
    - name: Publish the 'no-architecture' tag
      if: ${{ matrix.architecture == 'debian' }}
      run: |
        docker tag pedromr/collectd:${{ matrix.architecture }}-${{ github.ref }} pedromr/collectd:${{ github.ref }}
        docker push pedromr/collectd:${{ github.ref }}
