name: Test and merge pull request
on:
  pull_request:
jobs:
  build-and-test:
    strategy:
      matrix:
        architecture:
          - debian
          - alpine
          - alpine-full
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker build . --file ${{ matrix.architecture }}.Dockerfile --tag pedromr/collectd:test-${{ matrix.architecture }}
      - name: Test image
        run: |
          docker run --rm pedromr/collectd:test-${{ matrix.architecture }} -t -T
